---
title: "KOGPSY"
description: |
  Welcome to the website for *Kognitionspsychologie I* HS24 ([23263-01](https://vorlesungsverzeichnis.unibas.ch/de/home?id=284655))
  
  Instructor: [Rui Mata](https://psychologie.unibas.ch/de/personen/rui-mata/about-me/), University of Basel
  
  **Last updated:** `r format(Sys.time(), "%a %b %d %X %Y")`
  
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

![Thinking is simply using one's brain! <span>Photo by <a href="https://unsplash.com/@jessemartini?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Jesse Martini</a> on <a href="https://unsplash.com/s/photos/brain?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText">Unsplash</a></span>](photos/jesse-martini-Iod3vdjKE1E-unsplash.jpg)

# Session information

Sessions take place Tuesdays, 10.15-11.45, Pharmazentrum, Hörsaal 1. 

::: l-body
| # | Date     | Topic                         | Slides |
|---| ---------|-------------------------------|--------|
| 1 | 01.10.2024 | Session 1: Introduction | [pdf](presentations/KOGPSY_session1.pdf) |
| 2 | 08.10.2024 | Session 2: Intelligence | [pdf](presentations/KOGPSY_session2.pdf) |
| 3 | 15.10.2024 | Session 3: Perception | [pdf](presentations/KOGPSY_session3.pdf)  |
| 4 | 22.10.2024 | Session 4: Spatial cognition | [pdf](presentations/KOGPSY_session4.pdf) |
| 5 | 29.10.2024 | Session 5: Numerical cognition | [pdf](presentations/KOGPSY_session5.pdf) |
| 6 | 05.11.2024 | Session 6: Language | [pdf](presentations/KOGPSY_session6.pdf) |
| 7 | 19.11.2024 | Session 7: Knowing | [pdf](presentations/KOGPSY_session7.pdf) |
| 8 | 03.12.2024 | Session 8: Consciousness | [pdf](presentations/KOGPSY_session8.pdf) |
| 9 | 10.12.2024 | Session 9: Applications | [pdf](presentations/KOGPSY_session9.pdf) |
|10 | 17.12.2024 | Session 10: Wrap-up and Q&A | [pdf](presentations/KOGPSY_session10.pdf)  |
:::

*Note. Slides will be made available either shortly after each session*

# What is this course about?

This course aims to give a broad introduction to central topics in psychology, with a focus on mechanistic and pluralistic explanations of cognition. 

# What can you expect to learn?

By completing the course you can expect to...

- reflect about the need for mechanistic and pluralistic explanations in psychology
- learn about central theories and models in key areas of psychology
- become familiarized with common methods used in psychology
- learn about examples of applications of psychology to real-world contexts

# How should you use this website?

This website is designed to help course participants get an overview of the course, including a listing of recommended readings (see below) and the course slides (see table above). A [FAQ](https://adam.unibas.ch/goto_adam_crs_1736790.html) forum is available on ADAM. 

**Recommended Readings**

**Session 1**

Krakauer, J. W., Ghazanfar, A. A., Gomez-Marin, A., MacIver, M. A., & Poeppel, D. (2017). Neuroscience needs behavior: Correcting a reductionist bias. Neuron, 93(3), 480–490. http://doi.org/10.1016/j.neuron.2016.12.041

Nesse, R. M. (2013). Tinbergen’s four questions, organized: A response to Bateson and Laland. Trends in Ecology & Evolution, 28(12), 681–682. http://doi.org/10.1016/j.tree.2013.10.008

**Session 2**

Barbey, A. K. (2018). Network neuroscience theory of human intelligence. Trends in Cognitive Sciences, 22(1), 8–20. http://doi.org/10.1016/j.tics.2017.10.001.

Kovacs, K., & Conway, A. R. A. (2016). Process overlap theory: A unified account of the general factor of intelligence. Psychological Inquiry, 27(3), 151–177. http://doi.org/10.1080/1047840X.2016.1153946

**Session 3**

Gazzaniga, M. S., Ivry, R. B., & Mangun, G. R. (2018). Chapter 5: Sensation and Perception, Cognitive neuroscience: The biology of the mind (5th ed.). W.W. Norton & Company. 

Bracci, S., & Op De Beeck, H. P. (2023). Understanding human object vision: A picture is worth a thousand representations. Annual Review of Psychology, 74(1), 113–135. https://doi.org/10.1146/annurev-psych-032720-041031

**Session 4**

Burgess, N. (2008). Spatial cognition and the brain. Annals of the New York Academy of Sciences, 1124(1), 77–97. http://doi.org/10.1196/annals.1440.002

**Session 5**

Siemann, J., & Petermann, F. (2018). Evaluation of the Triple Code Model of numerical processing: Reviewing past neuroimaging and clinical findings. Research in Developmental Disabilities, 72, 106–117. http://doi.org/10.1016/j.ridd.2017.11.001

**Session 6**

Hickok, G., & Poeppel, D. (2015). Neural basis of speech perception. In M. J. Aminoff, F. Boller, & D. F. Swaab (Eds.), The Human Auditory System (Vol. 129, pp. 149–160). Elsevier. http://doi.org/https://doi.org/10.1016/B978-0-444-62630-1.00008-1

**Session 7**

Ralph, M. A. L., Jefferies, E., Patterson, K., & Rogers, T. T. (2016). The neural and computational bases of semantic cognition. Nature Reviews Neuroscience, 18(1), 42–55. http://doi.org/10.1038/nrn.2016.150

**Session 8**

Dehaene, S., Changeux, J.-P., Naccache, L., Sackur, J., & Sergent, C. (2006). Conscious, preconscious, and subliminal processing: A testable taxonomy. Trends in Cognitive Sciences, 10(5), 204–211. http://doi.org/10.1016/j.tics.2006.03.007

Dehaene, S., Lau, H., & Kouider, S. (2017). What is consciousness, and could machines have it? Science, 358(6362), 486–492. http://doi.org/10.1126/science.aan8871

**Session 9**

Castles, A., Rastle, K., & Nation, K. (2018). Ending the reading wars: Reading acquisition from novice to expert. Psychological Science in the Public Interest, 19(1), 5–51. https://doi.org/10.1177/1529100618772271

Dunlosky, J., Rawson, K. A., Marsh, E. J., Nathan, M. J., & Willingham, D. T. (2013). Improving students’ learning with effective learning techniques: Promising directions from cognitive and educational psychology. Psychological Science in the Public Interest, 14(1), 4–58. https://doi.org/10.1177/1529100612453266

~~Ecker, U. K. H., Lewandowsky, S., Cook, J., Schmid, P., Fazio, L. K., Brashier, N., Kendeou, P., Vraga, E. K., & Amazeen, M. A. (2022). The psychological drivers of misinformation belief and its resistance to correction. Nature Reviews Psychology, 1(1), 13–29. https://doi.org/10.1038/s44159-021-00006-y~~

**Session 10**

No recommended readings for this session.